name: Curse Packaging

on:
  push:
    tags:
     - '**-Release'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Package
        run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
